services:
  - type: web
    name: walmart-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker Hardcodewallmart_rag:app --bind 0.0.0.0:$PORT